# Generated by Django 2.1.8 on 2020-03-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('desc', models.TextField(verbose_name='简介')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('the_url', models.URLField(verbose_name='连接')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
