# Generated by Django 2.1.8 on 2020-03-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_auto_20200308_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='cover',
            field=models.ImageField(help_text='160*100', upload_to='cover'),
        ),
    ]
