# Generated by Django 2.1.8 on 2020-03-08 09:23

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_auto_20200308_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='文章内容'),
        ),
    ]
