# Generated by Django 2.1.8 on 2020-03-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_auto_20200308_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='desc',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='摘要'),
        ),
    ]
