# Generated by Django 2.1.8 on 2020-03-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_note_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='阅读量'),
        ),
    ]
