# Generated by Django 2.1.8 on 2020-03-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='日志内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
