# Generated by Django 2.1.8 on 2020-03-09 15:23

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='主题')),
                ('desc', models.TextField(max_length=100, verbose_name='说明')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('content', mdeditor.fields.MDTextField(verbose_name='文章内容')),
                ('cover', models.ImageField(help_text='190*230', upload_to='project_cover')),
            ],
        ),
    ]
